  /// \file OverlayEstimatorProcessor.hh
/*
 *
 * OverlayEstimatorProcessor.hh header template generated by fclass
 * Creation date : jeu. mai 9 2013
 * Copyright (c) CNRS , IPNL
 *
 * All Right Reserved.
 * Use and copying of these libraries and preparation of derivative works
 * based upon these libraries are permitted. Any copy of these libraries
 * must include this copyright notice.
 * 
 * @author : rete
 */


#ifndef OVERLAYESTIMATORPROCESSOR_HH
#define OVERLAYESTIMATORPROCESSOR_HH


#include <iostream> 
#include <string> 
#include <cstdlib> 
#include <cmath> 
#include <vector> 

#include "marlin/Processor.h"
#include "marlin/Exceptions.h"

#include "Monitoring/BaboonMonitoring.hh"
#include "Managers/DetectorManager.hh"
#include "Managers/AlgorithmManager.hh"
#include "Detector/SDHCAL.hh"
#include "Utilities/Globals.hh"
#include "Utilities/Internal.hh"



/* 
 * Class OverlayEstimatorProcessor
 * Inherits from base class marlin::Processor
 */ 

class OverlayEstimatorProcessor : public marlin::Processor {

	public:

		/*! Default Constructor */
		OverlayEstimatorProcessor();

		/*! Default Destructor */
		virtual ~OverlayEstimatorProcessor();


		virtual Processor *newProcessor()
			{ return new OverlayEstimatorProcessor(); }

		/*!
		 *
		 * @brief Init the procesor
		 *
		 */
		virtual void init();

		/*!
		 *
		 * @brief Process the run header.
		 *
		 */
		virtual void processRunHeader( EVENT::LCRunHeader* run  );

		/*!
		 *
		 * @brief  Process an event
		 *
		 */
		virtual void processEvent( EVENT::LCEvent * );

		/*!
		 *
		 * @brief Must be defined by the user. Check the event.
		 *
		 */
		virtual void check( EVENT::LCEvent * evt );

		/*!
		 *
		 * @brief called after processing all the events.
		 *
		 */
		virtual void end();

		/*!
		 *
		 *
		 *
		 */
		baboon::Return LoadSDHCALHits( baboon::SDHCAL *sdhcal , EVENT::LCEvent * );

	protected:

		baboon::SDHCAL *sdhcal;
		baboon::BaboonMonitoring *monitoring;
		baboon::DetectorManager *detectorManager;
		baboon::AlgorithmManager *algorithmManager;
		std::string overlayEstimatorMethod;
		std::string decoderString;
		std::string SDHCALCollectionName;
		baboon::StringVector IJKEncoding;
		std::string gearFile;


};  // class 


#endif  //  OVERLAYESTIMATORPROCESSOR_HH
