  /// \file ShowerProcessor.hh
/*
 *
 * ShowerProcessor.hh header template generated by fclass
 * Creation date : jeu. mai 9 2013
 * Copyright (c) CNRS , IPNL
 *
 * All Right Reserved.
 * Use and copying of these libraries and preparation of derivative works
 * based upon these libraries are permitted. Any copy of these libraries
 * must include this copyright notice.
 * 
 * @author : rete
 */


#ifndef SHOWERPROCESSOR_HH
#define SHOWERPROCESSOR_HH

#include <iostream> 
#include <string> 
#include <cstdlib> 
#include <cmath> 
#include <vector> 

#include "marlin/Processor.h"
#include "marlin/Exceptions.h"

#include "Monitoring/BaboonMonitoring.hh"

#include "Managers/DetectorManager.hh"
#include "Managers/AlgorithmManager.hh"
#include "Managers/AnalysisManager.hh"
#include "Managers/ClusteringManager.hh"
#include "Managers/CoreManager.hh"
#include "Managers/ShowerManager.hh"
#include "Managers/TrackManager.hh"

#include "Detector/SDHCAL.hh"

#include "Utilities/Globals.hh"
#include "Utilities/Internal.hh"



/* 
 * Class ShowerProcessor
 * Inherits from base class marlin::Processor
 */ 
class ShowerProcessor : public marlin::Processor {

	public:

		/*!
		 *
		 * Default Constructor
		 *
		 */
		ShowerProcessor();

		/*!
		 *
		 * Default Destructor
		 *
		 */
		virtual ~ShowerProcessor();

		/*!
		 *
		 * @brief Return a new processor
		 *
		 */
		virtual Processor *newProcessor()
			{ return new ShowerProcessor(); }

		/*!
		 *
		 * @brief Must be defined by the user. Init the processor
		 *
		 */
		virtual void init();

		/*!
		 *
		 * @brief Must be defined by the user. Process the run header.
		 *
		 */
		virtual void processRunHeader( EVENT::LCRunHeader* run  );

		/*!
		 *
		 * @brief Must be defined by the user. Process an event
		 *
		 */
		virtual void processEvent( EVENT::LCEvent * );

		/*!
		 *
		 * @brief Must be defined by the user. Check the event.
		 *
		 */
		virtual void check( EVENT::LCEvent * evt );

		/*!
		 *
		 * @brief Must be defined by the user. Called after processing all the events.
		 *
		 */
		virtual void end();

		/*!
		 *
		 * @brief  Load the sdhcal hits in the calorimeter from the LCEvent object
		 *
		 */
		baboon::Return LoadSDHCALHits( baboon::SDHCAL *sdhcal , EVENT::LCEvent * );

		/*!
		 *
		 * @brief  Clear the content for managers and detectors
		 *
		 */
		baboon::Return ClearContent();



	protected:

		// The sdhcal calorimeter instance
		baboon::SDHCAL *sdhcal;

		// monitoring
		baboon::BaboonMonitoring *monitoring;

		// managers
		baboon::DetectorManager *detectorManager;
		baboon::AlgorithmManager *algorithmManager;
		baboon::AnalysisManager *analysisManager;
		baboon::ClusteringManager *clusteringManager;
		baboon::CoreManager *coreManager;
		baboon::ShowerManager *showerManager;
		baboon::TrackManager *trackManager;

		// processor parameters
		bool enableMonitoring;
		std::string algorithmConfigFileName;
		std::string rootOutputFile;
		std::string displayMode; // for monitoring
		std::string decoderString; // for EVENT::CalorimeterHit
		std::string SDHCALCollectionName; // collection in the slcio file
		baboon::StringVector IJKEncoding; // the ijk encoding. default is ( I , J , K-1 )
		std::string gearFile; // for sdhcal geometry

		IO::LCWriter* lcWriter;
		std::string slcioOutputFile;

		// processor parameters
		double energy;


};  // class 


#endif  //  SHOWERPROCESSOR_HH
